language: node_js

node_js:
  - "6"
  - "8"

cache: yarn

sudo: false

notifications:
  email: false

script:
  - yarn test
  - yarn build

after_success:
  - yarn run test:coveralls