language: node_js

node_js:
  - "7"
  - "8"
  - "9"

cache:
  yarn: true
  directories:
    - node_modules

sudo: false

notifications:
  email: false

script:
  - yarn test
  - yarn build

after_success:
  - yarn run test:coveralls